apiVersion: v2
name: kubernetes-nodes
description: Worker node pool for a managed Kubernetes cluster
icon: /logos/kubernetes.svg
type: application
version: 0.0.0 # Placeholder, the actual version will be automatically set during the build process
appVersion: 1.32.6
